// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyFzrcXHAgU_Dmvm6Zaoq2_JsV0cEgIdA',
    appId: '1:650123506572:web:ab312698190c6ecc9adca9',
    messagingSenderId: '650123506572',
    projectId: 'chats-application-6e8ca',
    authDomain: 'chats-application-6e8ca.firebaseapp.com',
    databaseURL: 'https://chats-application-6e8ca-default-rtdb.firebaseio.com',
    storageBucket: 'chats-application-6e8ca.firebasestorage.app',
    measurementId: 'G-2DLG6PBHLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbf6Oj2JYTHpZ7r4HMfl05Kgd15qY2DOI',
    appId: '1:650123506572:android:43a24bff59c543ce9adca9',
    messagingSenderId: '650123506572',
    projectId: 'chats-application-6e8ca',
    databaseURL: 'https://chats-application-6e8ca-default-rtdb.firebaseio.com',
    storageBucket: 'chats-application-6e8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRlXHSmGVfzhtNvEOPpxWfy8p4KcRnHI',
    appId: '1:650123506572:ios:2dc97f5e2123884e9adca9',
    messagingSenderId: '650123506572',
    projectId: 'chats-application-6e8ca',
    databaseURL: 'https://chats-application-6e8ca-default-rtdb.firebaseio.com',
    storageBucket: 'chats-application-6e8ca.firebasestorage.app',
    iosBundleId: 'com.javven.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRlXHSmGVfzhtNvEOPpxWfy8p4KcRnHI',
    appId: '1:650123506572:ios:2dc97f5e2123884e9adca9',
    messagingSenderId: '650123506572',
    projectId: 'chats-application-6e8ca',
    databaseURL: 'https://chats-application-6e8ca-default-rtdb.firebaseio.com',
    storageBucket: 'chats-application-6e8ca.firebasestorage.app',
    iosBundleId: 'com.javven.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyFzrcXHAgU_Dmvm6Zaoq2_JsV0cEgIdA',
    appId: '1:650123506572:web:726eea172817e2779adca9',
    messagingSenderId: '650123506572',
    projectId: 'chats-application-6e8ca',
    authDomain: 'chats-application-6e8ca.firebaseapp.com',
    databaseURL: 'https://chats-application-6e8ca-default-rtdb.firebaseio.com',
    storageBucket: 'chats-application-6e8ca.firebasestorage.app',
    measurementId: 'G-DDLXK8ZQEM',
  );

}